# Generated by Django 3.2.3 on 2021-08-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
